version: '3'

services:
  # # Mongodb service
  # mongo_db:
  #   container_name: mongo
  #   image: mongo
  #   restart: always
  #   volumes:
  #     - ./data:/data/db
  #   hostname: mongo_db
  #   ports:
  #     - "27018:27017"
  #   # environment:
  #     # API_SERVER: http://localhost:5001

# volumes:
  # mongo_data: {}

  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    ports:
      - 3000:80
    env_file: client/.env.example

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - 5001:5001
    # depends_on:
    #   - mongo_db
    env_file: server/config/.env
