name: Build and Test

on: [pull_request, workflow_call]

permissions:
  id-token: write
  checks: write
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      REACT_ENV: 'production'
      REACT_APP_HOST: 'https://sandwicheck.app'
      REACT_APP_API_SERVER: 'https://api.sandwicheck.app'

    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test:ci

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: JEST Tests # Name of the check run which will be created
          path: ./client/reports/jest-*.xml # Path to test results
          reporter: jest-junit # Format of test results

      - name: Build
        run: |
          npm run build --if-present

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./client/build/

      - name: Build Docker Image
        run: |
          pwd
          ls -a
          docker build . --file ./docker/ui.Dockerfile -t sandwicheck-app-image
        working-directory: ./
